set1={1,2,3,4,3,2,1}
print(set1)
set1=set([1,2,3,2])
print(set1,"\n")
num_set=set([0,1,2,3,4,5])
print('original set:')
print(num_set)
num_set.pop()
print('after removing the first element from the said set:')
print(num_set,"\n")
my_set=set()
print(type(my_set))